version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '4001:4001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
    networks:
      - backend_network

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: testdocker
      MYSQL_USER: jb
      MYSQL_PASSWORD: rootpwd
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - backend_network

  frontend:
    build: ./frontend
    ports:
      - '4000:4000'
    environment:
      - REACT_APP_BACKEND_HOST=http://backend:4001
    networks:
      - frontend_network

volumes:
  db_data:

networks:
  backend_network:
  frontend_network:
