CREATE TABLE todos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL
);

  -- ALTER TABLE todos MODIFY COLUMN name VARCHAR(255) NOT NULL DEFAULT 'Default value';
  -- ALTER TABLE todos MODIFY COLUMN description VARCHAR(255) NOT NULL DEFAULT 'Default value';